apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
      - name: main
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: FRONTEND_ADDR
          value: "{{ .Values.ingress.host }}:80"
        - name: USERS
          value: "10"

