apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc-restore
spec:
  dataSource:
    name: storage-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath-class