apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: microservices-charts
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@gitlab.com/voitenkov/microservices-demo.git
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/infrastructure/deploy/charts/  