apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cartservice
  namespace: microservices-demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./infrastructure/deploy/charts/cartservice
      version: '0.4.x'
      sourceRef:
        kind: GitRepository
        name: microservices-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: registry.gitlab.com/voitenkov/microservices-demo/cartservice # {"$imagepolicy": "flux-system:cartservice:name"}
      tag: 0.0.195 # {"$imagepolicy": "flux-system:cartservice:tag"}
