apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: currencyservice
  namespace: microservices-demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./infrastructure/deploy/charts/currencyservice
      version: '0.4.x'
      sourceRef:
        kind: GitRepository
        name: microservices-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: registry.gitlab.com/voitenkov/microservices-demo/currencyservice # {"$imagepolicy": "flux-system:currencyservice:name"}
      tag: 0.0.195 # {"$imagepolicy": "flux-system:currencyservice:tag"}
