apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: microservices-demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./infrastructure/deploy/charts/frontend
      version: '0.21.x'
      sourceRef:
        kind: GitRepository
        name: microservices-charts
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: registry.gitlab.com/voitenkov/microservices-demo/frontend # {"$imagepolicy": "flux-system:frontend:name"}
      tag: 0.0.209 # {"$imagepolicy": "flux-system:frontend:tag"}
