---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: ./infrastructure/deploy/charts/prometheus
      version: '0.0.1'
      sourceRef:
        kind: GitRepository
        name: microservices-charts
        namespace: flux-system
      interval: 1m
