apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hipster-shop-prod
nameSuffix: -prod
commonLabels:
  app: cartservice-prod

resources:
- ../../base

patches:
- patch: |
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cartservice
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: cartservice-prod
      template:
        metadata:
          labels:
            app: cartservice-prod
        spec:
          containers:
          - name: server
            resources:
              requests:
                cpu: 200m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi
  target:
    kind: Deployment
- patch: |
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: cartservice
    spec:
      type: ClusterIP
      selector:
        app: cartservice-prod
  target:
    kind: Service
