tolerations:
  - operator: "Exists"

config:
  inputs: | 
      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On        
      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On 
  outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Host elasticsearch-master
          Logstash_Format On
          Logstash_Prefix kube
          Retry_Limit False
          tls On
          tls.verify Off
          http_user elastic
          http_passwd xyjXsVKZKLJ1UoL9
          Suppress_Type_Name On
      [OUTPUT]
          Name es
          Match host.*
          Host elasticsearch-master
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
          tls On
          tls.verify Off
          http_user elastic
          http_passwd xyjXsVKZKLJ1UoL9
          Suppress_Type_Name On
  customParsers: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
