image: kibana
imageTag: 8.5.1 

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

nodeSelector:
  node-group: infra-pool

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/acme-challenge-type: http01
  hosts:
    - host: kibana.k8s-dev.voytenkov.ru
      paths:
        - path: /
  tls:
    - secretName: kibana-tls
      hosts:
        - kibana.k8s-dev.voytenkov.ru

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "1Gi"