---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hipster-shop
commonLabels:
  app: cartservice

resources:
- ../../base

patches:
- patch: |
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cartservice
    spec:
      replicas: 1
  target:
    kind: Deployment
...
